python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -24 -21 -18 -15 -12 -9 -6 -3 0 3 6 9 12 15 18 21 24--save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -16 -14 -12 -10 -8 -6 -4 -2 0 2 4 6 8 10 12 14 16--save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8--save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -5 -4 -3 -2 -1 0 1 2 3 4 5 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -4 -3 -2 -1 0 1 2 3 4 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -8 -6 -4 -2 0 2 4 6 8 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -12 -9 -6 -3 0 3 6 9 12 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -16 -12 -8 -4 0 4 8 12 16 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -20 -15 -10 -5 0 5 10 15 20 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -3 -2 -1 0 1 2 3 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -6 -4 -2 0 2 4 6 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -9 -6 -3 0 3 6 9 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -12 -8 -4 0 4 8 12 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -15 -10 -5 0 5 10 15 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -2 -1 0 1 2  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -4 -2 0 2 4  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -6 -3 0 3 6  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -8 -4 0 4 8  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -10 -5 0 5 10 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -1 0 1  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -2 0 2  --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -3 0 3 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -4 0 4 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train
python3 My_Image_Segmentation/train.py --which_model -22 --batch_size 2 --continuous 1 --best_score 0.6 --epoch 5  --augmentation_prob 0.0 --continue_num -5 0 5 --save_model_path ./My_Image_Segmentation/models/0624_New_DeepLAB_with_different_frame --save_log_path My_Image_Segmentation/log/0624_New_DeepLAB_with_different_frame --train_data_path Medical_data/train